#pragma once

namespace user {
	enum StatusCodes: int {
		OK,
		ERROR_USER_IS_ADMIN,
		ERROR_NAME_IS_EMPTY,
		ERROR_USERNAME_IS_EMPTY,
		ERROR_PASSWORD_IS_EMPTY,
		ERROR_USER_NOT_FOUND,
		ERROR_NAME_IS_TOO_LONG,
		ERROR_USERNAME_IS_TOO_LONG,
		ERROR_PASSWORD_IS_TOO_LONG
	};
}
